Repository spooooony/Spoony-Server, pull requests merged in 2025-08, with the labels that each got.

#196 [FEAT] @AdminId 어노테이션을 이용하여 관리자 인증 로직 개선
  src/main/java/com/spoony/spoony_server/adapter/in/web/admin/AdminController.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/admin/AdminPersistenceAdapter.java
  src/main/java/com/spoony/spoony_server/application/auth/port/out/AdminPort.java
  src/main/java/com/spoony/spoony_server/application/port/command/admin/AdminDeletePostCommand.java
  src/main/java/com/spoony/spoony_server/application/port/command/admin/AdminDeleteUserCommand.java
  src/main/java/com/spoony/spoony_server/application/port/command/admin/AdminGetAllPostsCommand.java
  src/main/java/com/spoony/spoony_server/application/port/command/admin/AdminGetReportedPostsCommand.java
  src/main/java/com/spoony/spoony_server/application/port/command/admin/AdminGetReportedUsersCommand.java
  src/main/java/com/spoony/spoony_server/application/port/command/admin/AdminGetUserPostsCommand.java
  src/main/java/com/spoony/spoony_server/application/service/admin/AdminService.java
  src/main/java/com/spoony/spoony_server/global/message/auth/AuthErrorMessage.java
Labels: 💡FEAT, 🐻희재🍟

#198 [FEAT] Report, UserReport 도메인 및 Mapper에 createdAt 필드 반영하여 응답값 전달 로직 추가
  src/main/java/com/spoony/spoony_server/adapter/dto/admin/response/ReportedUserResponseDTO.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/report/mapper/ReportMapper.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/report/mapper/UserReportMapper.java
  src/main/java/com/spoony/spoony_server/application/service/admin/AdminService.java
  src/main/java/com/spoony/spoony_server/domain/report/Report.java
  src/main/java/com/spoony/spoony_server/domain/report/UserReport.java
Labels: 💡FEAT, 🔧FIX, 🐯건호🥩

#202 [FEAT] PostEntity에 is_deleted, deleted_at 속성 추가
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/post/db/PostEntity.java
Labels: 💡FEAT, 🐯건호🥩
