Repository spooooony/Spoony-Server, pull requests merged in 2025-10, with the labels that each got.

#235 Chore/#234
  .github/workflows/cicd-prod.yml
  src/main/java/com/spoony/spoony_server/SpoonyServerApplication.java
Labels: 🐇수민🥕

#238 [HOTFIX] user 테이블 유니크 제약조건 추가
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/user/db/UserEntity.java
Labels: 🔥HOTFIX, 🐻희재🍟

#233 [FIX] 찜카운트 관련 로직 수정 및 테스트
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/post/db/PostRepository.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/zzim/ZzimPersistenceAdapter.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/zzim/db/ZzimPostRepository.java
  src/test/java/com/spoony/spoony_server/ZzimCountTest.java
Labels: 🔧FIX, 🐻희재🍟
