Repository spooooony/Spoony-Server, pull requests merged in 2025-01, with the labels that each got.

#5 [FEAT] 장소 리스트 검색 API 구현 완료
  build.gradle
  src/main/java/com/spoony/spoony_server/common/message/PlaceErrorMessage.java
  src/main/java/com/spoony/spoony_server/domain/place/controller/PlaceController.java
  src/main/java/com/spoony/spoony_server/domain/place/entity/PlaceEntity.java
Labels: 🐁윤혁🧀, 💡FEAT

#7 [FEAT] 장소 DTO 구현, 장소 검색 API 반환 형식 수정
  src/main/java/com/spoony/spoony_server/domain/place/controller/PlaceController.java
  src/main/java/com/spoony/spoony_server/domain/place/dto/PlaceListResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/place/dto/PlaceResponseDTO.java
Labels: 🐁윤혁🧀, 💡FEAT

#14 [FEAT] 게시물 등록 구현
  src/main/java/com/spoony/spoony_server/common/message/CategoryErrorMessage.java
  src/main/java/com/spoony/spoony_server/common/message/SpoonErrorMessage.java
  src/main/java/com/spoony/spoony_server/common/message/UserErrorMessage.java
  src/main/java/com/spoony/spoony_server/domain/place/entity/PlaceEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/controller/PostController.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/request/PostCreateRequestDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/entity/PostCategoryEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/CategoryRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/MenuRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/PhotoRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/PostCategoryRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/domain/spoon/entity/ActivityEntity.java
  src/main/java/com/spoony/spoony_server/domain/spoon/entity/SpoonBalanceEntity.java
  src/main/java/com/spoony/spoony_server/domain/spoon/entity/SpoonHistoryEntity.java
  src/main/java/com/spoony/spoony_server/domain/spoon/repository/ActivityRepository.java
  src/main/java/com/spoony/spoony_server/domain/spoon/repository/SpoonBalanceRepository.java
  src/main/java/com/spoony/spoony_server/domain/spoon/repository/SpoonHistoryRepository.java
  src/main/java/com/spoony/spoony_server/domain/user/repository/UserRepository.java
Labels: 🐁윤혁🧀, 💡FEAT

#16 [FEAT] 게시물 등록 구현 2
  src/main/java/com/spoony/spoony_server/domain/post/repository/FeedRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/FollowRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/ZzimPostRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/domain/user/entity/FollowEntity.java
Labels: 🐁윤혁🧀, 💡FEAT

#18 [FIX] 메뉴 등록 요청 형식 변경
  src/main/java/com/spoony/spoony_server/domain/post/dto/request/PostCreateRequestDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
Labels: 🐁윤혁🧀, 🔧FIX

#20 [FEAT] 게시물 조회 API 구현
  src/main/java/com/spoony/spoony_server/common/message/PostErrorMessage.java
  src/main/java/com/spoony/spoony_server/common/message/UserErrorMessage.java
  src/main/java/com/spoony/spoony_server/domain/post/controller/PostController.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/entity/CategoryEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/entity/MenuEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/entity/PostCategoryEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/CategoryRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/MenuRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/PostCategoryRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/PostRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/domain/spoon/entity/SpoonBalanceEntity.java
  src/main/java/com/spoony/spoony_server/domain/user/controller/UserController.java
  src/main/java/com/spoony/spoony_server/domain/user/entity/RegionEntity.java
  src/main/java/com/spoony/spoony_server/domain/user/entity/UserEntity.java
  src/main/java/com/spoony/spoony_server/domain/user/repository/UserRepository.java
  src/main/java/com/spoony/spoony_server/domain/user/service/UserService.java
Labels: 🐇수민🥕, 💡FEAT

#21 [FEAT] S3 설정, 개인 정보 yml로 이동
  .github/workflows/cicd.yml
  .gitignore
  build.gradle
  src/main/java/com/spoony/spoony_server/common/message/S3ErrorMessage.java
  src/main/java/com/spoony/spoony_server/domain/place/controller/PlaceController.java
  src/main/java/com/spoony/spoony_server/infra/config/S3Config.java
  src/main/java/com/spoony/spoony_server/infra/service/AwsFileService.java
Labels: 🐁윤혁🧀, 💡FEAT

#24 [FEAT] 게시물 사진 S3 업로드
  src/main/java/com/spoony/spoony_server/domain/post/controller/PostController.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/PostCreateDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/request/PostCreateRequestDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/infra/service/AwsFileService.java
Labels: 🐁윤혁🧀, 💡FEAT

#26 [FEAT] 게시물 지도 리스트 추가 API 구현
  src/main/java/com/spoony/spoony_server/domain/post/controller/ZzimPostController.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/request/ZzimPostAddRequestDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/service/ZzimPostService.java
Labels: 🐇수민🥕, 💡FEAT

#27 [FEAT] 카테고리 Entity 수정, 카테고리 조회 API 구현
  src/main/java/com/spoony/spoony_server/domain/post/controller/PostController.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/CategoryMonoListResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/CategoryMonoResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/entity/CategoryEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/enums/CategoryType.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/CategoryRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
Labels: 🐁윤혁🧀, 💡FEAT

#35 [FEAT] 사용자 스푼 개수 조회 API 구현 완료
  src/main/java/com/spoony/spoony_server/domain/spoon/controller/SpoonController.java
  src/main/java/com/spoony/spoony_server/domain/spoon/dto/response/SpoonResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/spoon/service/SpoonService.java
Labels: 🐁윤혁🧀, 💡FEAT

#34 [FEAT] 게시물 떠먹기 API 구현
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/domain/spoon/controller/ScoopPostController.java
  src/main/java/com/spoony/spoony_server/domain/spoon/dto/request/ScoopPostRequestDTO.java
  src/main/java/com/spoony/spoony_server/domain/spoon/repository/ScoopPostRepository.java
  src/main/java/com/spoony/spoony_server/domain/spoon/service/ScoopPostService.java
Labels: 🐇수민🥕, 💡FEAT

#38 [FEAT] 지도 리스트 조회 API 구현
  src/main/java/com/spoony/spoony_server/common/message/PostErrorMessage.java
  src/main/java/com/spoony/spoony_server/domain/post/controller/PostController.java
  src/main/java/com/spoony/spoony_server/domain/post/controller/ZzimPostController.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/CategoryColorResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/ZzimCardListResponse.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/ZzimCardResponse.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/ZzimFocusResponse.java
  src/main/java/com/spoony/spoony_server/domain/post/entity/CategoryEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/entity/ZzimPostEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/PostCategoryRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/ZzimPostRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/domain/post/service/ZzimPostService.java
  src/main/java/com/spoony/spoony_server/domain/report/service/ReportService.java
  src/main/java/com/spoony/spoony_server/domain/spoon/service/ScoopPostService.java
Labels: 🐁윤혁🧀, 💡FEAT

#40 [FEAT] 지도 리스트 조회 구현 수정, 지도 장소 포커싱 구현
  src/main/java/com/spoony/spoony_server/common/message/PlaceErrorMessage.java
  src/main/java/com/spoony/spoony_server/domain/post/controller/PostController.java
  src/main/java/com/spoony/spoony_server/domain/post/controller/ZzimPostController.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/ZzimCardListResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/ZzimCardResponse.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/ZzimCardResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/ZzimFocusListResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/ZzimFocusResponse.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/ZzimFocusResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/entity/PhotoEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/PhotoRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/ZzimPostRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/domain/post/service/ZzimPostService.java
Labels: 🐁윤혁🧀, 💡FEAT

#43 [FEAT] 지도 리스트의 특정 장소 삭제 API 구현
  src/main/java/com/spoony/spoony_server/domain/post/controller/ZzimPostController.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/ZzimPostRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/service/ZzimPostService.java
Labels: 🐁윤혁🧀, 💡FEAT

#45 [FEAT] 사용자 정보 조회 API 구현
  src/main/java/com/spoony/spoony_server/common/message/UserErrorMessage.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/domain/post/service/ZzimPostService.java
  src/main/java/com/spoony/spoony_server/domain/report/service/ReportService.java
  src/main/java/com/spoony/spoony_server/domain/spoon/service/ScoopPostService.java
  src/main/java/com/spoony/spoony_server/domain/spoon/service/SpoonService.java
  src/main/java/com/spoony/spoony_server/domain/user/controller/UserController.java
  src/main/java/com/spoony/spoony_server/domain/user/dto/response/UserResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/user/service/UserService.java
Labels: 🐁윤혁🧀, 💡FEAT

#41 [FEAT] 게시물 조회 로직 수정- isSpoon추가,response에서 카테고리 관련 부분 수정
  src/main/java/com/spoony/spoony_server/domain/post/controller/PostController.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/ZzimPostRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/domain/spoon/repository/ScoopPostRepository.java
Labels: 🐇수민🥕, 💡FEAT

#49 [FEAT] 게시물 조회 로직 수정- 카테고리 반환방식 변경,이미지 조회 추가
  src/main/java/com/spoony/spoony_server/domain/location/entity/LocationDongEntity.java
  src/main/java/com/spoony/spoony_server/domain/location/entity/LocationGuEntity.java
  src/main/java/com/spoony/spoony_server/domain/location/entity/LocationStationEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/ZzimPostRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
Labels: 🐇수민🥕, 💡FEAT

#50 [FEAT] 지역 리스트 검색 API 구현 완료
  src/main/java/com/spoony/spoony_server/domain/location/controller/LocationController.java
  src/main/java/com/spoony/spoony_server/domain/location/dto/response/LocationResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/location/dto/response/LocationResponseListDTO.java
  src/main/java/com/spoony/spoony_server/domain/location/dto/response/LocationTypeDTO.java
  src/main/java/com/spoony/spoony_server/domain/location/entity/LocationEntity.java
  src/main/java/com/spoony/spoony_server/domain/location/entity/LocationTypeEntity.java
  src/main/java/com/spoony/spoony_server/domain/location/repository/LocationRepository.java
  src/main/java/com/spoony/spoony_server/domain/location/service/LocationService.java
Labels: 🐁윤혁🧀, 💡FEAT

#52 [FEAT] 카테고리 텍스트 색상 정보 추가
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/CategoryColorResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/entity/CategoryEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/domain/post/service/ZzimPostService.java
Labels: 🐁윤혁🧀, 💡FEAT

#57 [FEAT] 사용자 피드 조회 API 구현
  src/main/java/com/spoony/spoony_server/domain/post/controller/FeedController.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/request/FeedRequestDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/FeedResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/entity/FeedEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/FeedRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/PostCategoryRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/PostRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/service/FeedService.java
Labels: 🐇수민🥕, 💡FEAT

#56 [FEAT] 지도 위치 검색 API 구현 완료
  src/main/java/com/spoony/spoony_server/common/message/PostErrorMessage.java
  src/main/java/com/spoony/spoony_server/domain/post/controller/ZzimPostController.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/ZzimPlaceResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/service/ZzimPostService.java
Labels: 🐁윤혁🧀, 💡FEAT

#59 [REFACTOR] 사용자 피드 조회 API 리팩터링
  src/main/java/com/spoony/spoony_server/domain/post/controller/FeedController.java
  src/main/java/com/spoony/spoony_server/domain/post/service/FeedService.java
Labels: 🐇수민🥕, 🔨REFACTOR

#62 [FEAT] 떠먹기 API 피드 삭제 구현
  src/main/java/com/spoony/spoony_server/domain/post/controller/PostController.java
  src/main/java/com/spoony/spoony_server/domain/post/repository/FeedRepository.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/domain/spoon/controller/ScoopPostController.java
  src/main/java/com/spoony/spoony_server/domain/spoon/service/ScoopPostService.java
Labels: 🐁윤혁🧀, 💡FEAT

#63 [FEAT]사용자 피드 조회 API 구현 (카테고리 o)
  src/main/java/com/spoony/spoony_server/domain/post/controller/FeedController.java
  src/main/java/com/spoony/spoony_server/domain/post/service/FeedService.java
Labels: 🐇수민🥕, 💡FEAT

#65 [FEAT] 피드 조회 API 데이터 누락 수정, 구조 개선
  src/main/java/com/spoony/spoony_server/domain/post/controller/FeedController.java
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/FeedResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/service/FeedService.java
Labels: 🐁윤혁🧀, 💡FEAT

#69 [REFACTOR] API 엔드포인트 버전 정보 표시
  src/main/java/com/spoony/spoony_server/domain/location/controller/LocationController.java
  src/main/java/com/spoony/spoony_server/domain/place/controller/PlaceController.java
  src/main/java/com/spoony/spoony_server/domain/post/controller/FeedController.java
  src/main/java/com/spoony/spoony_server/domain/post/controller/PostController.java
  src/main/java/com/spoony/spoony_server/domain/report/controller/ReportController.java
  src/main/java/com/spoony/spoony_server/domain/spoon/controller/SpoonController.java
  src/main/java/com/spoony/spoony_server/domain/user/controller/UserController.java
  src/main/java/com/spoony/spoony_server/domain/zzim/controller/ZzimPostController.java
  src/main/java/com/spoony/spoony_server/domain/zzim/dto/response/request/PostCreateRequestDTO.java
Labels: 🐁윤혁🧀, 🔨REFACTOR

#71 [FIX] 지도 리스트 조회 API 이미지 누락 수정
  src/main/java/com/spoony/spoony_server/domain/post/repository/PhotoRepository.java
  src/main/java/com/spoony/spoony_server/domain/zzim/dto/response/ZzimCardResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/zzim/service/ZzimPostService.java
Labels: 🐁윤혁🧀, 🔧FIX

#73 [FIX] 색깔 카테고리 반환 시 카테고리 ID 추가
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/CategoryColorResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/service/FeedService.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
  src/main/java/com/spoony/spoony_server/domain/zzim/service/ZzimPostService.java
Labels: 🐁윤혁🧀, 🔧FIX

#76 [FEAT] 지역 검색 결과 HTML 특수 문자 필터링
  src/main/java/com/spoony/spoony_server/domain/place/controller/PlaceController.java
Labels: 🐁윤혁🧀, 💡FEAT

#77 [FIX] 스푼 개수에 따른 떠먹기 기능 제약 사항 추가
  src/main/java/com/spoony/spoony_server/common/message/SpoonErrorMessage.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
Labels: 🐇수민🥕, 🔧FIX

#79 [FEAT] HTML 특수 문자 제거 코드 리뷰 반영
  src/main/java/com/spoony/spoony_server/domain/place/controller/PlaceController.java
Labels: 🐁윤혁🧀, 💡FEAT

#81 [FEAT] 사용자 지도 리스트 조회 시 장소 개수 반환
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/zzim/dto/response/ZzimCardListResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/zzim/service/ZzimPostService.java
Labels: 🐁윤혁🧀, 💡FEAT

#83 [FEAT] 게시물 조회 시 현재 사용자가 작성자인지 나타내는 식별자 추가
  src/main/java/com/spoony/spoony_server/domain/post/dto/response/PostResponseDTO.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
Labels: 🐇수민🥕, 💡FEAT

#86 [FIX] 동 지역 검색 기준을 주소에서 거리로 임시 변경
  src/main/java/com/spoony/spoony_server/domain/zzim/service/ZzimPostService.java
Labels: 🐁윤혁🧀, 🔧FIX

#92 [FEAT] 게시물 조회 유저ID 반환 수정
  src/main/java/com/spoony/spoony_server/domain/post/entity/PostEntity.java
  src/main/java/com/spoony/spoony_server/domain/post/service/PostService.java
Labels: 🐇수민🥕, 💡FEAT

#94 [FEAT] 피드 카테고리 조회 시 로컬 수저 필터링 추가
  src/main/java/com/spoony/spoony_server/domain/post/service/FeedService.java
Labels: 🐁윤혁🧀, 💡FEAT

#95 [FEAT] 지역 주소 대신 지역명을 기준으로 필터링하도록 수정
  src/main/java/com/spoony/spoony_server/domain/zzim/service/ZzimPostService.java
Labels: 🐁윤혁🧀, 💡FEAT
