Repository spooooony/Spoony-Server, pull requests merged in 2025-09, with the labels that each got.

#211 [FEAT] 애플 탈퇴 구현
  .github/workflows/cicd-dev.yml
  src/main/java/com/spoony/spoony_server/adapter/auth/dto/request/PlatformRequestDTO.java
  src/main/java/com/spoony/spoony_server/adapter/auth/dto/request/UserSignupDTO.java
  src/main/java/com/spoony/spoony_server/adapter/auth/in/web/AuthController.java
  src/main/java/com/spoony/spoony_server/adapter/auth/out/persistence/AppleRefreshTokenAdapter.java
  src/main/java/com/spoony/spoony_server/adapter/auth/verification/apple/AppleClientSecretGenerator.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/user/db/AppleRefreshTokenEntity.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/user/db/AppleRefreshTokenRepository.java
  src/main/java/com/spoony/spoony_server/application/auth/port/in/LoginUseCase.java
  src/main/java/com/spoony/spoony_server/application/auth/port/in/WithdrawUseCase.java
  src/main/java/com/spoony/spoony_server/application/auth/port/out/AppleRefreshTokenPort.java
  src/main/java/com/spoony/spoony_server/application/auth/service/AppleService.java
  src/main/java/com/spoony/spoony_server/application/auth/service/AuthService.java
  src/main/java/com/spoony/spoony_server/global/auth/encryptor/AppleRefreshTokenEncryptor.java
  src/main/java/com/spoony/spoony_server/global/message/auth/AuthErrorMessage.java
  src/test/java/com/spoony/spoony_server/AppleRefreshTokenUpsertTest.java
Labels: 💡FEAT, 🐻희재🍟

#219 [HOTFIX] 스푼 사용 동시성 이슈
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/post/PostPersistenceAdapter.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/post/db/ScoopPostEntity.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/spoon/SpoonPersistenceAdapter.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/spoon/db/ScoopPostRepository.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/spoon/db/SpoonBalanceRepository.java
  src/main/java/com/spoony/spoony_server/application/port/out/post/PostPort.java
  src/main/java/com/spoony/spoony_server/application/port/out/spoon/SpoonPort.java
  src/main/java/com/spoony/spoony_server/application/service/post/PostService.java
  src/main/java/com/spoony/spoony_server/global/message/business/SpoonErrorMessage.java
  src/test/java/com/spoony/spoony_server/ScoopPostTest.java
Labels: 🔥HOTFIX, 🐻희재🍟

#227 [HOTFIX] 게시글 중복 생성 이슈 해결
  src/main/java/com/spoony/spoony_server/adapter/in/web/post/PostController.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/post/PostPersistenceAdapter.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/post/db/PostEntity.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/post/db/PostRepository.java
  src/main/java/com/spoony/spoony_server/application/port/out/post/PostPort.java
  src/main/java/com/spoony/spoony_server/application/service/post/PostService.java
  src/main/java/com/spoony/spoony_server/global/event/AfterCommitEventListener.java
  src/main/java/com/spoony/spoony_server/global/event/AfterCommitWrapper.java
  src/main/java/com/spoony/spoony_server/global/event/PostCreatedEventProbe.java
  src/main/java/com/spoony/spoony_server/global/message/business/PostErrorMessage.java
  src/test/java/com/spoony/spoony_server/PostCreateConcurrentTest.java
Labels: 🔥HOTFIX, 🐻희재🍟

#232 [RELEASE] v1.1.0
  .github/workflows/cicd-prod.yml
  .gitignore
  src/main/java/com/spoony/spoony_server/adapter/dto/user/response/ProfileImageResponseDTO.java
  src/main/java/com/spoony/spoony_server/adapter/dto/user/response/UserBlockResponseDTO.java
  src/main/java/com/spoony/spoony_server/adapter/dto/user/response/UserResponseDTO.java
  src/main/java/com/spoony/spoony_server/adapter/dto/user/response/UserSimpleResponseDTO.java
  src/main/java/com/spoony/spoony_server/adapter/in/web/post/PostController.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/post/PostPersistenceAdapter.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/post/db/PostEntity.java
  src/main/java/com/spoony/spoony_server/adapter/out/persistence/post/db/PostRepository.java
  src/main/java/com/spoony/spoony_server/application/port/out/post/PostPort.java
  src/main/java/com/spoony/spoony_server/application/service/post/PostService.java
  src/main/java/com/spoony/spoony_server/global/config/SwaggerConfig.java
  src/main/java/com/spoony/spoony_server/global/event/AfterCommitEventListener.java
  src/main/java/com/spoony/spoony_server/global/event/AfterCommitWrapper.java
  src/main/java/com/spoony/spoony_server/global/event/PostCreatedEventProbe.java
  src/main/java/com/spoony/spoony_server/global/message/business/PostErrorMessage.java
  src/main/java/com/spoony/spoony_server/global/support/ProfileCdn.java
  src/test/java/com/spoony/spoony_server/PostCreateConcurrentTest.java
Labels: 🎯 RELEASE
